FROM jenkins/agent:alpine-jdk17

USER root

# Update and install required packages
RUN apk add --no-cache python3
RUN apk add --no-cache py3-pip

# Set Java 21 as the default
ENV JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
ENV PATH="$JAVA_HOME/bin:$PATH"

# Verify Java version
RUN java -version

USER jenkins